CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY, started DOUBLE PRECISION NOT NULL);
CREATE TABLE IF NOT EXISTS recordings(id TEXT PRIMARY KEY, session_id TEXT NOT NULL,
  start DOUBLE PRECISION NOT NULL, duration DOUBLE PRECISION NOT NULL, media TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS segments(id TEXT PRIMARY KEY, recording_id TEXT NOT NULL,
  session_id TEXT NOT NULL, start DOUBLE PRECISION NOT NULL, "end" DOUBLE PRECISION NOT NULL, audio TEXT NOT NULL,
  state TEXT NOT NULL DEFAULT 'queued', text TEXT, attempts INTEGER NOT NULL DEFAULT 0,
  next_at DOUBLE PRECISION NOT NULL DEFAULT 0, owner TEXT, lease DOUBLE PRECISION NOT NULL DEFAULT 0,
  submitted_at DOUBLE PRECISION, error TEXT, audio_url TEXT);
CREATE INDEX IF NOT EXISTS queue_due ON segments(state,next_at,lease);
CREATE INDEX IF NOT EXISTS segment_session_range ON segments(session_id,start,"end");
