CREATE SCHEMA IF NOT EXISTS diting_live;
CREATE TABLE IF NOT EXISTS diting_live.sessions (
 id TEXT PRIMARY KEY,
 run_id TEXT UNIQUE NOT NULL,
 teacher TEXT NOT NULL,
 started DOUBLE PRECISION NOT NULL,
 live BOOLEAN NOT NULL DEFAULT true
);
